package com.sixgod.dllo.anews.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTENTION".
 */
public class Attention {

    private Long id;
    private String url;
    private String title;

    public Attention() {
    }

    public Attention(Long id) {
        this.id = id;
    }

    public Attention(Long id, String url, String title) {
        this.id = id;
        this.url = url;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
