package com.sixgod.dllo.anews.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sixgod.dllo.anews.db.Attention;

import com.sixgod.dllo.anews.db.AttentionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attentionDaoConfig;

    private final AttentionDao attentionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attentionDaoConfig = daoConfigMap.get(AttentionDao.class).clone();
        attentionDaoConfig.initIdentityScope(type);

        attentionDao = new AttentionDao(attentionDaoConfig, this);

        registerDao(Attention.class, attentionDao);
    }
    
    public void clear() {
        attentionDaoConfig.getIdentityScope().clear();
    }

    public AttentionDao getAttentionDao() {
        return attentionDao;
    }

}
